export const GET_SHOWS = "GET_SHOWS";
export const SET_PAGE = "SET_PAGE";
export const SET_SINGLE_SHOW = "SET_SINGLE_SHOW";
export const GET_SHOW_INFO_EPISODES = "GET_SHOW_INFO_EPISODES";
export const GET_SHOW_INFO_SEASONS = 'GET_SHOW_INFO_SEASONS'
